services:
  web:
    image: nginx:1.29.1-alpine
    container_name: nginx
    volumes:
      - ./nginx_dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8020:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
     - myappnet
  myapp:
    image: myapp:stable
    container_name: myapp
    restart: always
    environment:
      - AUTH__EMAIL__HOST=smtp.yandex.ru
      - AUTH__EMAIL__PORT=465
      - AUTH__EMAIL__USERNAME=user
      - AUTH__EMAIL__PASSWORD=password
      - AUTH__EMAIL__SENDER=user
      - AUTH__RABBITMQ__HOST=rabbitmq
      - AUTH__TEST_RABBITMQ__HOST=rabbit
      - AUTH__DB__HOST=database
      - AUTH__TEST_DB__HOST=database
    #ports:
    # - 8000:8000
    networks:
      - myappnet
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:13.22-alpine3.22
    container_name: postgres_alpine
    hostname: database
    restart: always
    # set shared memory limit when using docker compose
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth
    # ports:
    #   - 5432:5432
    networks:
      - myappnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'
        reservations:
          cpus: '0.05'
          memory: '256M'


  adminer:
    image: adminer
    restart: always
    networks:
      - myappnet
    ports:
      - 8080:8080


  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.1.3-management-alpine
    restart: always
    networks:
      - myappnet
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      #- 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  myappnet:
    driver: bridge